### ISSUE TITLE
npm install png fails via png fails with the following output

### ISSUE THREAD

**Issue by vicapow** [pkrumins/node-png#12]
> png@2.0.0 install /Users/victorpowell/Documents/examples/node/png/node_modules/png
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /opt/node 
Checking for library png                 : yes 
'configure' finished successfully (0.536s)
Waf: Entering directory `/Users/victorpowell/Documents/examples/node/png/node_modules/png/build'
[1/8] cxx: src/common.cpp -> build/Release/src/common_1.o
[2/8] cxx: src/png_encoder.cpp -> build/Release/src/png_encoder_1.o
[3/8] cxx: src/png.cpp -> build/Release/src/png_1.o
[4/8] cxx: src/fixed_png_stack.cpp -> build/Release/src/fixed_png_stack_1.o
../src/png.cpp: In static member function ‘static v8::Handle<v8::Value> Png::PngEncodeAsync(const v8::Arguments&)’:
../src/png.cpp:206: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/png.cpp:206: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/fixed_png_stack.cpp: In static member function ‘static v8::Handle<v8::Value> FixedPngStack::PngEncodeAsync(const v8::Arguments&)’:
../src/fixed_png_stack.cpp:263: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/fixed_png_stack.cpp:263: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory`/Users/victorpowell/Documents/examples/node/png/node_modules/png/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx png.cpp -> png_1.o}
 -> task failed (err #1): 
    {task: cxx fixed_png_stack.cpp -> fixed_png_stack_1.o}
npm ERR! error installing png@2.0.0 Error: png@2.0.0 install: `node-waf configure build`
npm ERR! error installing png@2.0.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing png@2.0.0     at ChildProcess.<anonymous> (/opt/node/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing png@2.0.0     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing png@2.0.0     at maybeExit (child_process.js:336:16)
npm ERR! error installing png@2.0.0     at Process.onexit (child_process.js:371:5)
npm ERR! png@2.0.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the png@2.0.0 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/opt/node/bin/npm" "install" "png"
npm ERR! cwd /Users/victorpowell/Documents/examples/node/png
npm ERR! node -v v0.5.10
npm ERR! npm -v 1.0.103
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/victorpowell/Documents/examples/node/png/npm-debug.log
npm not ok
victorpowell:png victorpowell$ npm owner ls png
pkrumins peteris.krumins@gmail.com

**Comment by pkrumins** [comment]
I am not sure why that is happening

**Comment by miikka** [comment]
I'm having the same issue. I changed the return type of function `EIO_PngEncode` in all the three implementations to `void`. This made it compile but I have no idea if that is a sensible thing to do.

**Comment by pkrumins** [comment]
Which node version? We use node 0.4 in Browserling and it all works perfectly.

**Comment by miikka** [comment]
I'm running node 0.6.1, on OS X Lion. The C++ compiler is i686-apple-darwin11-llvm-g++-4.2 version 4.2.1, the default compiler that comes with Xcode 4.2, if that matters.

**Comment by pkrumins** [comment]
It doesn't work on node 0.6.1. We use node 0.4 at Browserling. There are no plans to migrate to 0.6 any time soon, so I will not be fixing this issue.

**Comment by rajanram** [comment]
I am running 0.4.11 I am having the same Issue and I also trying to use macports for libpng any guide on that too?

**Comment by harcek** [comment]
hi @rajanram, do you have the exact errors as mentioned in the issue or they are more like those mentioned here https://github.com/pkrumins/node-png/issues/3. The thing is that the NPM expects png libs (those installed as libpng via mac ports) in different paths as they are deployed - at least it was my case. And then, I had to build it manually via `sudo node-waf configure build` from the dir of the module. There is more written down within comments of issue#3.

**Comment by pkrumins** [comment]
Someone just patched node-png to work on node 0.6.x!

**Comment by rajanram** [comment]
Oh.. Nice thanks very much

**Comment by petermilan** [comment]
Works fine.
