### ISSUE TITLE
npm install produces error

### ISSUE THREAD

**Issue by OscarGodson** [pkrumins/node-png#31]
```
 master node-flickr-store $ npm install png
npm http GET https://registry.npmjs.org/png
npm http 304 https://registry.npmjs.org/png

> png@3.0.1 install /Users/oscar/Dropbox/projects/node-flickr-store/node_modules/png
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libpng --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:415:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:757:12)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/oscar/Dropbox/projects/node-flickr-store/node_modules/png
gyp ERR! node -v v0.10.2
gyp ERR! node-gyp -v v0.9.3
gyp ERR! not ok
npm ERR! png@3.0.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the png@3.0.1 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "png"
npm ERR! cwd /Users/oscar/Dropbox/projects/node-flickr-store
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/oscar/Dropbox/projects/node-flickr-store/npm-debug.log
npm ERR! not ok code 0
```

All other npm modules install fine.

**Comment by pkrumins** [comment]
It says why in the error:

`/bin/sh: pkg-config: command not found`
