### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by shobhitsharma** [pkrumins/node-png#35]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:106:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:790:12)
gyp ERR! System Linux 3.8.0-29-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/shobhit/Workspace/js-vnc-demo-project-master/node_modules/png
gyp ERR! node -v v0.11.6
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by shobhitsharma** [comment]
Jizz. Found it wasnt registered to npm.

```
sudo npm install -g node-gyp
git clone git@github.com:pkrumins/node-png.git
cd node-png
node-gyp configure build
```

Does it.
