### ISSUE TITLE
Unable to install or build on Mac OS X Yosemite

### ISSUE THREAD

**Issue by daviddias** [pkrumins/node-png#42]
Hi! I'm having some issues getting this module to run, namely:

When I try to install

```
$ npm i png                                                                      
npm WARN package.json crp-raytracer@0.0.4 No repository field.
npm WARN package.json crp-stream-client@0.0.12 No repository field.
npm http request GET https://registry.npmjs.org/png
npm http 304 https://registry.npmjs.org/png
|
> png@3.0.3 install /Users/david/Documents/Code/crp-raytracer/node_modules/png
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libpng --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/Documents/Code/crp-raytracer/node_modules/png
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "png"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.4
npm ERR! code ELIFECYCLE

npm ERR! png@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the png@3.0.3 install script.
npm ERR! This is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

When I try to build

``` bash
$ node-gyp configure build                                                       
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.32 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/Documents/Code/node-png/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/.node-gyp/0.10.32/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/david/.node-gyp/0.10.32',
gyp info spawn args   '-Dmodule_root_dir=/Users/david/Documents/Code/node-png',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libpng --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/david/Documents/Code/node-png
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

What might be I missing? Thank you!

**Comment by aamirshah** [comment]
:+1:

**Comment by pkrumins** [comment]
The error message says what the problem is:

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libpng --libs' returned exit status 127. while trying to load binding.gyp

You don't have pkg-config installed.

Pkg-config is used by the build system to setups paths and flags for includes and libraries for gcc.

**Comment by kk86bioinfo** [comment]
I am having issue with Yosemite as well.

```
node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.33 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/Users/kk_loke86/.nvm/v0.10.33/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kk_loke86/github/opensource/node-vnc/angular-vnc-master/proxy/node_modules/node-png/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kk_loke86/.nvm/v0.10.33/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/root/.node-gyp/0.10.33/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/Users/kk_loke86/github/opensource/node-vnc/angular-vnc-master/proxy/node_modules/node-png',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/png/src/png_encoder.o
In file included from ../src/png_encoder.cpp:3:
../src/png_encoder.h:4:10: error: 'png.h' file not found with <angled> include;
      use "quotes" instead
#include <png.h>
         ^~~~~~~
         "png.h"
../src/png_encoder.h:19:36: error: unknown type name 'png_structp'
    static void png_chunk_producer(png_structp png_ptr, png_bytep data, ...
                                   ^
../src/png_encoder.h:19:57: error: unknown type name 'png_bytep'
    static void png_chunk_producer(png_structp png_ptr, png_bytep data, ...
                                                        ^
../src/png_encoder.h:19:73: error: unknown type name 'png_size_t'; did you mean
      'vm_size_t'?
  ...png_chunk_producer(png_structp png_ptr, png_bytep data, png_size_t length);
                                                             ^~~~~~~~~~
                                                             vm_size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/mach/i386/vm_types.h:112:20: note: 
      'vm_size_t' declared here
typedef uintptr_t               vm_size_t;
                                ^
../src/png_encoder.cpp:7:32: error: unknown type name 'png_structp'
PngEncoder::png_chunk_producer(png_structp png_ptr, png_bytep data, png_...
                               ^
../src/png_encoder.cpp:7:53: error: unknown type name 'png_bytep'
PngEncoder::png_chunk_producer(png_structp png_ptr, png_bytep data, png_...
                                                    ^
../src/png_encoder.cpp:7:69: error: unknown type name 'png_size_t'; did you mean
      'vm_size_t'?
  ...png_ptr, png_bytep data, png_size_t length)
                              ^~~~~~~~~~
                              vm_size_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/mach/i386/vm_types.h:112:20: note: 
      'vm_size_t' declared here
typedef uintptr_t               vm_size_t;
                                ^
../src/png_encoder.cpp:48:5: error: unknown type name 'png_structp'
    png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING...
    ^
../src/png_encoder.cpp:48:51: error: use of undeclared identifier
      'PNG_LIBPNG_VER_STRING'
    png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING...
                                                  ^
../src/png_encoder.cpp:52:5: error: unknown type name 'png_infop'
    png_infop info_ptr = png_create_info_struct(png_ptr);
    ^
../src/png_encoder.cpp:60:22: error: use of undeclared identifier
      'PNG_COLOR_TYPE_RGB'
        color_type = PNG_COLOR_TYPE_RGB;
                     ^
../src/png_encoder.cpp:63:22: error: use of undeclared identifier
      'PNG_COLOR_TYPE_GRAY'
        color_type = PNG_COLOR_TYPE_GRAY;
                     ^
../src/png_encoder.cpp:66:22: error: use of undeclared identifier
      'PNG_COLOR_TYPE_RGB_ALPHA'
        color_type = PNG_COLOR_TYPE_RGB_ALPHA;
                     ^
../src/png_encoder.cpp:73:5: error: unknown type name 'png_bytep'
    png_bytep *row_pointers = NULL;
    ^
../src/png_encoder.cpp:83:9: error: unknown type name 'png_bytep'
        png_bytep *row_pointers = (png_bytep *)malloc(sizeof(png_bytep) ...
        ^
../src/png_encoder.cpp:83:36: error: use of undeclared identifier 'png_bytep'
        png_bytep *row_pointers = (png_bytep *)malloc(sizeof(png_bytep) ...
                                   ^
../src/png_encoder.cpp:83:47: error: expected expression
        png_bytep *row_pointers = (png_bytep *)malloc(sizeof(png_bytep) ...
                                              ^
17 errors generated.
make: *** [Release/obj.target/png/src/png_encoder.o] Error 1
```

**Comment by jamesseanwright** [comment]
Hi kk86bioinfo, I am also experiencing the same issue. Were you able to resolve it?

**Comment by alekseymya** [comment]
The same error on Yosemite. Any solutions?

**Comment by jamesseanwright** [comment]
I reinstalled the library that had `node-png` as a dependency and the problem went away for me. So sorry that I can't be more helpful!

**Comment by fernandofranca** [comment]
I have the same issue. 
libpng seems to be a tricky subject for Mac users, as stated here (https://www.npmjs.com/package/depthcam).
I've tried to follow the steps and build it by hand, but unfortunately it didn't help at all.

**Comment by jpdevries** [comment]
I am also unable to install on Yosemite. 

<details>
<summary>

Log info</summary>



``` bash
j15:makeanico jP$ npm -v
3.10.3
j15:makeanico jP$ node -v
v6.3.1
j15:makeanico jP$ npm install png

> png@3.0.3 install /Users/jP/Sites/10kapart/makeanico/node_modules/png
> node-gyp rebuild

  CXX(target) Release/obj.target/png/src/common.o
../src/common.cpp:10:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/jP/.node-gyp/6.3.1/include/node/v8.h:904:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:11:37: error: no member named 'New' in 'v8::String'
    return Exception::Error(String::New(msg));
                            ~~~~~~~~^
../src/common.cpp:16:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/jP/.node-gyp/6.3.1/include/node/v8.h:904:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/common.cpp:17:12: error: use of undeclared identifier 'ThrowException'; did you
      mean 'ErrorException'?
    return ThrowException(ErrorException(msg));
           ^~~~~~~~~~~~~~
           ErrorException
../src/common.cpp:8:1: note: 'ErrorException' declared here
ErrorException(const char *msg)
^
../src/common.cpp:17:27: error: no viable conversion from 'Handle<v8::Value>'
      (aka 'v8::Local<v8::Value>') to 'const char *'
    return ThrowException(ErrorException(msg));
                          ^~~~~~~~~~~~~~~~~~~
../src/common.cpp:8:28: note: passing argument to parameter 'msg' here
ErrorException(const char *msg)
                           ^
5 errors generated.
make: *** [Release/obj.target/png/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jP/Sites/10kapart/makeanico/node_modules/png
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN cellfill@0.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "install" "png"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! png@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the png@3.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the png package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs png
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls png
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jP/Sites/10kapart/makeanico/npm-debug.log
```

</details>
