### ISSUE TITLE
cannot build under nodejs v4.1.2 with node-gyp v3.0.3

### ISSUE THREAD

**Issue by guodong** [pkrumins/node-png#50]
cannot build under nodejs v4.1.2 with node-gyp v3.0.3

**Comment by guodong** [comment]
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.2 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/cloudware-ws/png/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/4.1.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/4.1.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/cloudware-ws/png',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/ubuntu/cloudware-ws/png/build'
  CXX(target) Release/obj.target/png/src/common.o
In file included from /home/ubuntu/.node-gyp/4.1.2/include/node/node.h:42:0,
                 from ../src/common.h:4,
                 from ../src/common.cpp:3:
/home/ubuntu/.node-gyp/4.1.2/include/node/v8.h: In function ‘v8::Handle<v8::Value> ErrorException(const char*)’:
/home/ubuntu/.node-gyp/4.1.2/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/common.cpp:10:17: error: within this context
     HandleScope scope;
                 ^
../src/common.cpp:11:29: error: ‘New’ is not a member of ‘v8::String’
     return Exception::Error(String::New(msg));
                             ^
In file included from /home/ubuntu/.node-gyp/4.1.2/include/node/node.h:42:0,
                 from ../src/common.h:4,
                 from ../src/common.cpp:3:
/home/ubuntu/.node-gyp/4.1.2/include/node/v8.h: In function ‘v8::Handle<v8::Value> VException(const char*)’:
/home/ubuntu/.node-gyp/4.1.2/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/common.cpp:16:17: error: within this context
     HandleScope scope;
                 ^
../src/common.cpp:17:46: error: ‘ThrowException’ was not declared in this scope
     return ThrowException(ErrorException(msg));
                                              ^
../src/common.cpp: In function ‘v8::Handle<v8::Value> ErrorException(const char*)’:
../src/common.cpp:12:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/common.cpp: In function ‘v8::Handle<v8::Value> VException(const char*)’:
../src/common.cpp:18:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/png/src/common.o] Error 1
make: Leaving directory `/home/ubuntu/cloudware-ws/png/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/ubuntu/cloudware-ws/png
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by vladmyr** [comment]
Same here.
- node 4.2.3;
- node-gyp 3.0.3.

**Comment by daviddias** [comment]
Same here, subscribing this issue, looking forward for updates :D

**Comment by mattgodbolt** [comment]
There's a load of changes that went into node in v0.12 and above (see [here](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/) for example). I took a quick look at the code and it's a reasonably large change to support newer nodes as well as older ones.

**Comment by GuillaumeLeclerc** [comment]
So it won't be supported ?
